# Generated by Django 5.2.8 on 2025-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('url', models.CharField(max_length=500, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cهای فوتر',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فوتر')),
                ('copyright_text', models.CharField(default='تمامی حقوق توسط تیم برنامه نویسی امیران محفوظ است.', max_length=500, verbose_name='متن کپی\u200cرایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('instagram', 'اینستاگرام'), ('twitter', 'توییتر'), ('linkedin', 'لینکدین'), ('youtube', 'یوتیوب'), ('aparat', 'آپارات')], max_length=50, verbose_name='پلتفرم')),
                ('url', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گروه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('links', models.ManyToManyField(related_name='groups', to='core.footerlink', verbose_name='لینک\u200cها')),
            ],
            options={
                'verbose_name': 'گروه لینک فوتر',
                'verbose_name_plural': 'گروه\u200cهای لینک فوتر',
                'ordering': ['order', 'id'],
            },
        ),
    ]
