# Generated by Django 5.2.8 on 2025-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footerlink_footersettings_socialmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_jalali_date', models.BooleanField(default=True, verbose_name='استفاده از تاریخ شمسی')),
                ('site_title', models.CharField(default='پنل مدیریت دیجیتو', max_length=100, verbose_name='عنوان سایت')),
                ('site_header', models.CharField(default='مدیریت دیجیتو', max_length=100, verbose_name='هدر سایت')),
                ('site_index_title', models.CharField(default='پنل مدیریت', max_length=100, verbose_name='عنوان صفحه اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات پنل ادمین',
                'verbose_name_plural': 'تنظیمات پنل ادمین',
            },
        ),
    ]
