# Generated by Django 5.2.8 on 2025-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='show_hidden_models',
            field=models.BooleanField(default=False, verbose_name='نمایش مدل\u200cهای پنهان شده (حالت پیشرفته)'),
        ),
    ]
