# Generated by Django 5.2.8 on 2025-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='سایز بهینه: 1200x800 پیکسل (نسبت 3:2)', null=True, upload_to='about/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='سایز بهینه: بنر اصلی (Hero): 1920x384 پیکسل | بنر کناری: 300x600 پیکسل (نسبت 1:2) | بنر پایین: 1200x675 پیکسل (نسبت 16:9)', upload_to='banners/', verbose_name='تصویر'),
        ),
    ]
