"""
Django settings for Digito project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# ======================
# Paths
# ======================
BASE_DIR = Path(__file__).resolve().parent.parent

# ======================
# Security
# ======================
SECRET_KEY = config('SECRET_KEY', default="django-insecure-f1u+9g&qd+9xu+n+s828bxkrl0w6()uf7_78a+e3hq(9edvzv^")
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# ======================
# Custom User Model
# ======================
AUTH_USER_MODEL = 'accounts.MyUser'

# ======================
# Admin Panel Settings
# ======================
ADMIN_SITE_TITLE = config('ADMIN_SITE_TITLE', default='دیجیتو')
ADMIN_SITE_HEADER = config('ADMIN_SITE_HEADER', default='پنل مدیریت دیجیتو')
ADMIN_SITE_INDEX_TITLE = config('ADMIN_SITE_INDEX_TITLE', default='خوش آمدید به پنل مدیریت')

# ======================
# OTP Settings (Kavenegar)
# ======================
KAVENEGAR_API_KEY = config('KAVENEGAR_API_KEY', default='')
KAVENEGAR_SENDER = config('KAVENEGAR_SENDER', default='10001001001')
OTP_USE_KAVENEGAR = config('OTP_USE_KAVENEGAR', default=False, cast=bool)
OTP_MAX_REQUESTS_PER_HOUR = config('OTP_MAX_REQUESTS_PER_HOUR', default=5, cast=int)
OTP_MAX_REQUESTS_PER_DAY = config('OTP_MAX_REQUESTS_PER_DAY', default=10, cast=int)
OTP_EXPIRY_MINUTES = config('OTP_EXPIRY_MINUTES', default=5, cast=int)

# ======================
# Payment Gateway (Zarinpal)
# ======================
ZARINPAL_MERCHANT_ID = config('ZARINPAL_MERCHANT_ID', default='')
ZARINPAL_SANDBOX = config('ZARINPAL_SANDBOX', default=True, cast=bool)
ZARINPAL_ACTIVE = config('ZARINPAL_ACTIVE', default=False, cast=bool)

# ======================
# Installed Apps
# ======================
INSTALLED_APPS = [
    # Django defaults
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    
    # Third-party
    'mptt',
    
    # Local apps
    'core',
    'accounts',
    'blog',
    'cart',
    'orders',
    'products',
]

# ======================
# Middleware
# ======================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Digito.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "contex_processors.contex_processors.cart_context",
                "contex_processors.contex_processors.categories_context",
                "contex_processors.contex_processors.contact_info_context",
                "contex_processors.contex_processors.footer_context",
            ],
        },
    },
]

WSGI_APPLICATION = "Digito.wsgi.application"

# ======================
# Database
# ======================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ======================
# Password Validation
# ======================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ======================
# Internationalization
# ======================
LANGUAGE_CODE = "fa-ir"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ======================
# Static files
# ======================
STATIC_URL = "static/"
STATIC_ROOT = Path(config('STATIC_ROOT', default=str(BASE_DIR / "staticfiles")))
STATICFILES_DIRS = [str(BASE_DIR / "static")]

# ======================
# Media files
# ======================
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(config('MEDIA_ROOT', default=str(BASE_DIR / "media")))

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": str(MEDIA_ROOT),
            "base_url": MEDIA_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ======================
# Default primary key field type
# ======================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ======================
# Logging Configuration
# ======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'zarinpal': {
            'format': '{levelname} {asctime} [ZarinPal] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'zarinpal_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'zarinpal.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'zarinpal',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'orders.payment': {
            'handlers': ['zarinpal_file', 'console', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'orders.views': {
            'handlers': ['zarinpal_file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
