# Generated by Django 5.2 on 2025-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "مرد"), ("female", "زن")],
                max_length=50,
                null=True,
            ),
        ),
    ]
