# Generated by Django 5.2 on 2025-07-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_myuser_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="date_of_birth",
        ),
    ]
