# Generated by Django 5.2.8 on 2025-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='سایز بهینه: 1200x600 پیکسل (نسبت 2:1) یا 1200x800 پیکسل (نسبت 3:2). فرمت پیشنهادی: JPG یا WebP', null=True, upload_to='blog/', verbose_name='تصویر'),
        ),
    ]
