# Generated by Django 5.2 on 2025-07-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان محصول")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "english_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات محصول")),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی انبار"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="عکس محصول",
                    ),
                ),
                (
                    "is_amazing",
                    models.BooleanField(
                        default=False, verbose_name="شگفت\u200cانگیز است"
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="پرفروش است"),
                ),
                (
                    "color_choices",
                    models.JSONField(blank=True, null=True, verbose_name="رنگ\u200cها"),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="جنس بدنه"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="مقدار RAM"
                    ),
                ),
                (
                    "battery",
                    models.CharField(blank=True, max_length=100, verbose_name="باتری"),
                ),
                (
                    "cpu",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="پردازنده"
                    ),
                ),
                (
                    "warranty_months",
                    models.PositiveSmallIntegerField(
                        default=18, verbose_name="گارانتی (ماه)"
                    ),
                ),
                (
                    "satisfaction_percent",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="درصد رضایت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
