# Generated by Django 5.2 on 2025-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_bestseller",
        ),
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.IntegerField(default=0, verbose_name="فروش ها"),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.IntegerField(default=0, verbose_name="بازدید ها"),
        ),
    ]
