# Generated by Django 5.2.8 on 2025-11-07 13:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


def rebuild_mptt_tree(apps, schema_editor):
    """Rebuild کردن درخت MPTT برای دسته‌بندی‌های موجود بعد از اضافه شدن فیلدهای MPTT"""
    Category = apps.get_model('products', 'Category')
    
    # استفاده از mptt.utils.rebuild_tree برای rebuild کردن درخت
    try:
        from mptt.utils import rebuild_tree
        rebuild_tree(Category, order_insertion_by=['name'])
    except Exception:
        # اگر rebuild_tree کار نکرد، از روش دستی استفاده می‌کنیم
        # تمام دسته‌بندی‌ها را به‌روزرسانی می‌کنیم
        categories = Category.objects.all()
        for category in categories:
            category.save()


def reverse_rebuild(apps, schema_editor):
    """Reverse migration - هیچ کاری انجام نمی‌دهد"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_remove_product_battery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        # Rebuild کردن درخت MPTT بعد از اضافه شدن فیلدها
        migrations.RunPython(rebuild_mptt_tree, reverse_rebuild),
    ]
