# Generated by Django 5.2.8 on 2025-11-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_category_level_category_lft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['key'], 'verbose_name': 'مشخصات محصول', 'verbose_name_plural': 'مشخصات محصولات'},
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bought_by_author',
            field=models.BooleanField(default=False, verbose_name='خریداری شده توسط نویسنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recommendation',
            field=models.BooleanField(default=False, verbose_name='توصیه می\u200cکند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.color', verbose_name='رنگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product', verbose_name='محصول'),
        ),
    ]
