# Generated by Django 5.2.8 on 2025-11-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_color_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(help_text='سایز بهینه: 200x200 پیکسل (مربع). فرمت پیشنهادی: PNG با پس\u200cزمینه شفاف', upload_to='brands/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='سایز بهینه: 800x800 پیکسل (مربع) یا 800x600 پیکسل (نسبت 4:3). فرمت پیشنهادی: JPG یا WebP', upload_to='products/gallery/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند'),
        ),
    ]
