# Generated by Django 5.2.8 on 2025-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_alter_productimage_image_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='سایز بهینه: 200x200 پیکسل (مربع). فرمت پیشنهادی: PNG یا JPG', null=True, upload_to='categories/', verbose_name='تصویر'),
        ),
    ]
